name: python-meetup
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - python-gmsh
  - meshio
  - fenics-dolfinx
  - mpich
  - pyvista
  - notebook
  - matplotlib
  - ipywidgets 
  - sympy
  - ipyvtklink 
  - panel
  - rise
